apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-test-spring 
spec:
  selector:
    matchLabels:
      app: api-test-spring
  template:
    metadata:
      labels:
        app: api-test-spring
    spec:
      containers:
        - image: okteto.dev/java-gradle-api-test-spring:1.0.0
          name: api-test-spring

---

apiVersion: v1
kind: Service
metadata:
  name: api-test-spring
spec:
  type: ClusterIP
  ports:
    - name: "api-test-spring"
      port: 8080
  selector:
    app: api-test-spring

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-test-spring
  annotations:
    dev.okteto.com/generate-host: api-test-spring
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: api-test-spring
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific